[tool.poetry]
name = "carservices"
version = "0.1.0"
description = ""
authors = ["ricklon <rick.rickanderson@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
argparse = "^1.4.0"
tqdm = "^4.48.0"
pyserial = "^3.4"
Pillow = "^7.2.0"
picamera = "^1.13"
"rpi.gpio" = "^0.7.0"
tensorflow = {url = "https://github.com/PINTO0309/Tensorflow-bin/raw/master/tensorflow-1.15.0-cp37-cp37m-linux_armv7l.whl"}
keras = "2.3.1"
scipy = {url = "https://www.piwheels.org/simple/scipy/scipy-1.5.1-cp37-cp37m-linux_armv7l.whl#sha256=a03df78474a6fefd3322b9fe44fe1e38b26cb2737c2bba0f96233cc02dde04a9"}

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
car_runner = "carservices.carRunner:main"
test_pihat = "carservices.pihattest:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
