[tool.poetry]
name = "carservices"
version = "0.2.0"
description = ""
authors = ["ricklon <rick.rickanderson@gmail.com>"]


[[tool.poetry.source]]
name = "piwheels"
url = "https://www.piwheels.org/simple"
secondary = true

[tool.poetry.dependencies]
python = "^3.7"
tensorflow = {url = "https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl"}
"RPi.GPIO" = "^0.7.0"
pyserial = "^3.5"
picamera = "^1.13"


[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
car_runner = "carservices.carRunner:main"
test_pihat = "carservices.pihattest:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
